### ISSUE TITLE
Offer logo for Reading-Diary

### ISSUE THREAD

**Issue by familqasimov** [candalo/reading-diary#1]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-2](https://user-images.githubusercontent.com/36432269/39409610-3a423540-4bfb-11e8-83a2-bbcbb32bd168.png)

**Comment by candalo** [comment]
Hi Famil! Initially I'm working on this app for the Udacity's Nanodegree course, thus I have to work alone for the first version of the app. After I finish the first version (required for the course), I'll keep working on the app, and I even intend to publish it in the store. So after I finish the first version I would like to use the logo you created. I thought it was pretty cool :)

Thanks!

**Comment by familqasimov** [comment]
I wish you success in your work. You can now use this logo for free. If you want, I can send a PR for this logo.

**Comment by familqasimov** [comment]
Can I submit a pull request for this logo?
